input {
  file {
    path => "/var/lib/docker/containers/*/*.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb"
    codec => json
  }
}

filter {
  if [attrs][com.docker.compose.service] {
    mutate {
      add_field => { "service" => "%{[attrs][com.docker.compose.service]}" }
    }
  } else if [attrs][container_name] {
    mutate {
      add_field => { "service" => "%{[attrs][container_name]}" }
    }
  }

  if [log] {
    mutate {
      rename => { "log" => "message" }
    }
  }

  if [time] {
    date {
      match => ["time", "ISO8601"]
      target => "@timestamp"
    }
  }

  grok {
    match => { "path" => "/var/lib/docker/containers/%{DATA:container_id}/%{DATA}.log" }
    tag_on_failure => []
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ai-service-logs-%{+YYYY.MM.dd}"
  }
}
